//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCV
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTION
    {
        public ACTION()
        {
            this.GROUPS = new HashSet<GROUP>();
        }
    
        public int ID { get; set; }
        public string ACTIONNAME { get; set; }
        public string ACTIONURL { get; set; }
    
        public virtual ICollection<GROUP> GROUPS { get; set; }
    }
}
