//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCV
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP
    {
        public GROUP()
        {
            this.ACTIONS = new HashSet<ACTION>();
            this.NGUOIDUNGs = new HashSet<NGUOIDUNG>();
        }
    
        public int ID { get; set; }
        public string TENGROUP { get; set; }
    
        public virtual ICollection<ACTION> ACTIONS { get; set; }
        public virtual ICollection<NGUOIDUNG> NGUOIDUNGs { get; set; }
    }
}
